//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinEcomDomain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VinEcom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VinEcom() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VinEcomDomain.Resources.VinEcom", typeof(VinEcom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu về toà nhà..
        /// </summary>
        public static string VINECOM_BUILDING_NOT_EXIST {
            get {
                return ResourceManager.GetString("VINECOM_BUILDING_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại không chính xác..
        /// </summary>
        public static string VINECOM_CURRENT_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("VINECOM_CURRENT_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại. Vui lòng thử lại..
        /// </summary>
        public static string VINECOM_CUSTOMER_BLOCK_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_CUSTOMER_BLOCK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không tồn tại. Vui lòng thử lại..
        /// </summary>
        public static string VINECOM_CUSTOMER_NOT_FOUND {
            get {
                return ResourceManager.GetString("VINECOM_CUSTOMER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không phù hợp..
        /// </summary>
        public static string VINECOM_EMAIL_INVALID_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_EMAIL_INVALID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn ảnh không được để trống..
        /// </summary>
        public static string VINECOM_IMAGE_URL_EMPTY_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_IMAGE_URL_EMPTY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng đường dẫn ảnh không phù hợp..
        /// </summary>
        public static string VINECOM_IMAGE_URL_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_IMAGE_URL_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng đơn hàng phải lớn hơn 0..
        /// </summary>
        public static string VINECOM_NUM_OF_ORDERS_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_NUM_OF_ORDERS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm vào giỏ hàng. Vui lòng thử lại..
        /// </summary>
        public static string VINECOM_ORDER_ADDTOCART_FAILED {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_ADDTOCART_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm trong giỏ hàng và sản phẩm được thêm không cùng một cửa hàng..
        /// </summary>
        public static string VINECOM_ORDER_ADDTOCART_PRODUCT_NOT_SAME_STORE {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_ADDTOCART_PRODUCT_NOT_SAME_STORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm vào giỏ hàng. Số lượng tối thiểu là 1..
        /// </summary>
        public static string VINECOM_ORDER_ADDTOCART_QUANTITY_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_ADDTOCART_QUANTITY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận đơn thất bại. Vui lòng thử lại..
        /// </summary>
        public static string VINECOM_ORDER_ASSIGN_SHIPPER_FAILED {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_ASSIGN_SHIPPER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy đơn thất bại. Vui lòng thử lại..
        /// </summary>
        public static string VINECOM_ORDER_CANCEL_FAILED {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_CANCEL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán thất bại. Vui lòng thử lại..
        /// </summary>
        public static string VINECOM_ORDER_CHECKOUT_FAILED {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_CHECKOUT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu về đơn hàng..
        /// </summary>
        public static string VINECOM_ORDER_DETAIL_NOT_FOUND {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_DETAIL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu về đơn hàng..
        /// </summary>
        public static string VINECOM_ORDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa sản phẩm khỏi giỏ hàng. Vui lòng thử lại..
        /// </summary>
        public static string VINECOM_ORDER_REMOVE_FROM_CART_FAILED {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_REMOVE_FROM_CART_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã huỷ.
        /// </summary>
        public static string VINECOM_ORDER_STATUS_CANCEL {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_STATUS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string VINECOM_ORDER_STATUS_DONE {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_STATUS_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chuẩn bị.
        /// </summary>
        public static string VINECOM_ORDER_STATUS_PREPARING {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_STATUS_PREPARING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang giao.
        /// </summary>
        public static string VINECOM_ORDER_STATUS_SHIPPING {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_STATUS_SHIPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ mục trang yêu cầu tối thiểu là 0..
        /// </summary>
        public static string VINECOM_PAGE_INDEX_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_PAGE_INDEX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước trang phải lớn hơn 0..
        /// </summary>
        public static string VINECOM_PAGE_SIZE_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_PAGE_SIZE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thức uống.
        /// </summary>
        public static string VINECOM_PRODUCT_CATEGORY_BEVERAGE {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_CATEGORY_BEVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân loại sản phẩm này không tồn tại..
        /// </summary>
        public static string VINECOM_PRODUCT_CATEGORY_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_CATEGORY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món ăn.
        /// </summary>
        public static string VINECOM_PRODUCT_CATEGORY_FOOD {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_CATEGORY_FOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhu yếu phẩm.
        /// </summary>
        public static string VINECOM_PRODUCT_CATEGORY_NECESSITY {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_CATEGORY_NECESSITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký sản phẩm không thành công. Lỗi hệ thống..
        /// </summary>
        public static string VINECOM_PRODUCT_CREATE_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_CREATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá tiền sản phẩm không hợp lệ. Chi chấp nhận giá trị là số và số tiền lớn hơn 0..
        /// </summary>
        public static string VINECOM_PRODUCT_CREATE_INVALID_ORIGINAL_PRICE_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_CREATE_INVALID_ORIGINAL_PRICE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm không được để trống..
        /// </summary>
        public static string VINECOM_PRODUCT_CREATE_NAME_EMPTY_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_CREATE_NAME_EMPTY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm phải từ {0} - {1} ký tự..
        /// </summary>
        public static string VINECOM_PRODUCT_CREATE_NAME_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_CREATE_NAME_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm không tồn tại..
        /// </summary>
        public static string VINECOM_PRODUCT_NOT_EXIST {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá thành công..
        /// </summary>
        public static string VINECOM_RATING_SUCCESS {
            get {
                return ResourceManager.GetString("VINECOM_RATING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá sản phẩm chỉ cho phép giá trị từ {0} - {1}..
        /// </summary>
        public static string VINECOM_RATING_VALUE_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_RATING_VALUE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác thất bại. Lỗi hệ thống.
        /// </summary>
        public static string VINECOM_SERVER_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành đơn hàng thất bại. Vui lòng thử lại..
        /// </summary>
        public static string VINECOM_SHIPPER_FINISH_ORDER_FAILED {
            get {
                return ResourceManager.GetString("VINECOM_SHIPPER_FINISH_ORDER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biển số xe không được để trống..
        /// </summary>
        public static string VINECOM_SHIPPER_SIGNUP_PLATE_EMPTY_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_SHIPPER_SIGNUP_PLATE_EMPTY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang hoạt động.
        /// </summary>
        public static string VINECOM_SHIPPER_STATUS_AVAILABLE {
            get {
                return ResourceManager.GetString("VINECOM_SHIPPER_STATUS_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang giao hàng.
        /// </summary>
        public static string VINECOM_SHIPPER_STATUS_ENROUTE {
            get {
                return ResourceManager.GetString("VINECOM_SHIPPER_STATUS_ENROUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hoạt động.
        /// </summary>
        public static string VINECOM_SHIPPER_STATUS_OFFLINE {
            get {
                return ResourceManager.GetString("VINECOM_SHIPPER_STATUS_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quán cafe.
        /// </summary>
        public static string VINECOM_STORE_CATEGORY_BEVERAGE {
            get {
                return ResourceManager.GetString("VINECOM_STORE_CATEGORY_BEVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quán ăn.
        /// </summary>
        public static string VINECOM_STORE_CATEGORY_FOOD {
            get {
                return ResourceManager.GetString("VINECOM_STORE_CATEGORY_FOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạp hoá.
        /// </summary>
        public static string VINECOM_STORE_CATEGORY_GROCERY {
            get {
                return ResourceManager.GetString("VINECOM_STORE_CATEGORY_GROCERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân loại cửa hàng không phù hợp..
        /// </summary>
        public static string VINECOM_STORE_CATEGORY_NOT_EXIST_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_STORE_CATEGORY_NOT_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại. Lỗi hệ thống..
        /// </summary>
        public static string VINECOM_STORE_CHANGE_STATUS_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_STORE_CHANGE_STATUS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu về cửa hàng.
        /// </summary>
        public static string VINECOM_STORE_NOT_EXIST {
            get {
                return ResourceManager.GetString("VINECOM_STORE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoa hồng trích xuất từ doanh thu cửa hàng phải nằm trong khoảng từ {0}% đến {1}%..
        /// </summary>
        public static string VINECOM_STORE_REGISTER_COMMISSION_RANGE_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_STORE_REGISTER_COMMISSION_RANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cửa hàng phải từ {0} - {1} ký tự..
        /// </summary>
        public static string VINECOM_STORE_REGISTER_NAME_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_STORE_REGISTER_NAME_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký cửa hàng thành công..
        /// </summary>
        public static string VINECOM_STORE_REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("VINECOM_STORE_REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ thẩm quyền truy cập..
        /// </summary>
        public static string VINECOM_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("VINECOM_UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công..
        /// </summary>
        public static string VINECOM_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("VINECOM_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại hoặc mật khẩu không chính xác..
        /// </summary>
        public static string VINECOM_USER_AUTHORIZE_FAILED {
            get {
                return ResourceManager.GetString("VINECOM_USER_AUTHORIZE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh không tồn tại..
        /// </summary>
        public static string VINECOM_USER_AVATAR_URL_NOT_FOUND {
            get {
                return ResourceManager.GetString("VINECOM_USER_AVATAR_URL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại này đã được sử dụng..
        /// </summary>
        public static string VINECOM_USER_REGISTER_PHONE_DUPLICATED {
            get {
                return ResourceManager.GetString("VINECOM_USER_REGISTER_PHONE_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công..
        /// </summary>
        public static string VINECOM_USER_REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("VINECOM_USER_REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không thể để trống..
        /// </summary>
        public static string VINECOM_USER_SIGNUP_NAME_EMPTY_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_USER_SIGNUP_NAME_EMPTY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên phải từ {0} - {1} ký tự..
        /// </summary>
        public static string VINECOM_USER_SIGNUP_NAME_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_USER_SIGNUP_NAME_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không thể để trống..
        /// </summary>
        public static string VINECOM_USER_SIGNUP_PASSWORD_EMPTY_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_USER_SIGNUP_PASSWORD_EMPTY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải từ {0} - {1} ký tự. .
        /// </summary>
        public static string VINECOM_USER_SIGNUP_PASSWORD_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_USER_SIGNUP_PASSWORD_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không thể để trống..
        /// </summary>
        public static string VINECOM_USER_SIGNUP_PHONE_EMPTY_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_USER_SIGNUP_PHONE_EMPTY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ. Vui lòng kiểm tra lại cú pháp..
        /// </summary>
        public static string VINECOM_USER_SIGNUP_PHONE_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("VINECOM_USER_SIGNUP_PHONE_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe máy.
        /// </summary>
        public static string VINECOM_VEHICLE_TYPE_MOTORBIKE {
            get {
                return ResourceManager.GetString("VINECOM_VEHICLE_TYPE_MOTORBIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phương tiện không phù hợp..
        /// </summary>
        public static string VINECOM_VEHICLE_TYPE_NOT_EXIST {
            get {
                return ResourceManager.GetString("VINECOM_VEHICLE_TYPE_NOT_EXIST", resourceCulture);
            }
        }
    }
}
